webtalk_init -webtalk_dir D:/MyDiSIC/VHDL/Ver33/KUL_DiSIC/KUL_DiSIC.sim/sim_1/behav/xsim/xsim.dir/TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb 28 17:43:10 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211253938_177879426_210718070_762" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fc54f3dc-a2bb-4fb8-b397-3d30efec2117" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "12b798e81db44e1a934fa2eb5f0d7ca1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "31" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "5466044 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "723.73_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14392_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4183688531 -regid "211253938_177879426_210718070_762" -xml D:/MyDiSIC/VHDL/Ver33/KUL_DiSIC/KUL_DiSIC.sim/sim_1/behav/xsim/xsim.dir/TB_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/MyDiSIC/VHDL/Ver33/KUL_DiSIC/KUL_DiSIC.sim/sim_1/behav/xsim/xsim.dir/TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/MyDiSIC/VHDL/Ver33/KUL_DiSIC/KUL_DiSIC.sim/sim_1/behav/xsim/xsim.dir/TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
